# app/schemas.py
from pydantic import BaseModel
from typing import Optional

# Base schema (common attributes)
class MortgageBase(BaseModel):
    applicant: str   # <--- Changed from 'string' to 'str'
    score: int
    amount: float
    rate: float
    term: int
    address: str     # <--- Changed from 'string' to 'str'
    ltv: float
    dti: float
    status: str
    date: str

# Schema for creating a record (ID is generated by DB, so we don't send it)
class MortgageCreate(MortgageBase):
    pass

# Schema for reading a record (includes ID)
class Mortgage(MortgageBase):
    id: int

    class Config:
        from_attributes = True
